<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.7.9 on win32)" generated="20230517 11:00:11.584" rpa="false" schemaversion="3">
<suite id="s1" name="Form" source="\\hovdifssv.tisconet.com\hovdipsm01$\zchanatuch\My Documents\insurance-automate-tester\E-Submission\form.robot">
<test id="s1-t1" name="Insured" line="6">
<kw name="common.Open website" type="SETUP">
<msg timestamp="20230517 11:00:11.689" level="FAIL">No keyword with name 'common.Open website' found.</msg>
<status status="FAIL" starttime="20230517 11:00:11.688" endtime="20230517 11:00:11.689"/>
</kw>
<status status="FAIL" starttime="20230517 11:00:11.683" endtime="20230517 11:00:11.689">Setup failed:
No keyword with name 'common.Open website' found.</status>
</test>
<status status="FAIL" starttime="20230517 11:00:11.596" endtime="20230517 11:00:11.701"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Form">Form</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230517 11:00:11.676" level="ERROR">Error in file '\\hovdifssv.tisconet.com\hovdipsm01$\zchanatuch\My Documents\insurance-automate-tester\E-Submission\form.robot' on line 2: Resource file '..sourceimport.robot' does not exist.</msg>
</errors>
</robot>
